export const quotes = [
  // --- Motivation ---
  { text: "The best way to get started is to quit talking and begin doing.", topic: "motivation", author: "Walt Disney" },
  { text: "Don't watch the clock; do what it does. Keep going.", topic: "motivation", author: "Sam Levenson" },
  { text: "Dream big and dare to fail.", topic: "motivation", author: "Norman Vaughan" },
  { text: "The harder you work for something, the greater you'll feel when you achieve it.", topic: "motivation" },
  { text: "Success usually comes to those who are too busy to be looking for it.", topic: "motivation", author: "Henry David Thoreau" },
  { text: "Push yourself, because no one else is going to do it for you.", topic: "motivation" },
  { text: "Sometimes later becomes never. Do it now.", topic: "motivation" },
  { text: "Wake up with determination. Go to bed with satisfaction.", topic: "motivation" },
  { text: "Little things make big days.", topic: "motivation" },
  { text: "You don't have to be great to start, but you have to start to be great.", topic: "motivation", author: "Zig Ziglar" },
  { text: "Your limitation—it's only your imagination.", topic: "motivation" },
  { text: "Great things never come from comfort zones.", topic: "motivation" },

  // --- Success ---
  { text: "Success is not final; failure is not fatal: it is the courage to continue that counts.", topic: "success", author: "Winston Churchill" },
  { text: "Don't be afraid to give up the good to go for the great.", topic: "success", author: "John D. Rockefeller" },
  { text: "Opportunities don't happen. You create them.", topic: "success", author: "Chris Grosser" },
  { text: "The road to success and the road to failure are almost exactly the same.", topic: "success", author: "Colin R. Davis" },
  { text: "Don't let yesterday take up too much of today.", topic: "success", author: "Will Rogers" },
  { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", topic: "success", author: "Jim Rohn" },
  { text: "I find that the harder I work, the more luck I seem to have.", topic: "success", author: "Thomas Jefferson" },
  { text: "Success usually comes to those who are too busy to be looking for it.", topic: "success", author: "Henry David Thoreau" },
  { text: "The way to get started is to quit talking and begin doing.", topic: "success", author: "Walt Disney" },
  { text: "Action is the foundational key to all success.", topic: "success", author: "Pablo Picasso" },
  { text: "Strive not to be a success, but rather to be of value.", topic: "success", author: "Albert Einstein" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", topic: "success", author: "Winston Churchill" },

  // --- Love ---
  { text: "Love the life you live. Live the life you love.", topic: "love", author: "Bob Marley" },
  { text: "To love and be loved is to feel the sun from both sides.", topic: "love", author: "David Viscott" },
  { text: "Love is composed of a single soul inhabiting two bodies.", topic: "love", author: "Aristotle" },
  { text: "The best thing to hold onto in life is each other.", topic: "love", author: "Audrey Hepburn" },
  { text: "Where there is love there is life.", topic: "love", author: "Mahatma Gandhi" },
  { text: "Love recognizes no barriers.", topic: "love", author: "Maya Angelou" },
  { text: "We are shaped and fashioned by what we love.", topic: "love", author: "Johann Wolfgang von Goethe" },
  { text: "Love is when the other person's happiness is more important than your own.", topic: "love", author: "H. Jackson Brown, Jr." },
  { text: "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.", topic: "love", author: "Lao Tzu" },
  { text: "Love does not dominate; it cultivates.", topic: "love", author: "Johann Wolfgang von Goethe" },
  { text: "Love is the only force capable of transforming an enemy into a friend.", topic: "love", author: "Martin Luther King Jr." },
  { text: "In the end, the love you take is equal to the love you make.", topic: "love", author: "The Beatles" },

  // --- Mindfulness ---
  { text: "Breathe. It's just a bad day, not a bad life.", topic: "mindfulness" },
  { text: "The present moment is filled with joy and happiness. If you are attentive, you will see it.", topic: "mindfulness", author: "Thich Nhat Hanh" },
  { text: "Mindfulness is the aware, balanced acceptance of the present experience.", topic: "mindfulness", author: "Sylvia Boorstein" },
  { text: "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.", topic: "mindfulness", author: "Thich Nhat Hanh" },
  { text: "Each morning we are born again. What we do today matters most.", topic: "mindfulness", author: "Buddha" },
  { text: "The mind is everything. What you think you become.", topic: "mindfulness", author: "Buddha" },
  { text: "The best way to capture moments is to pay attention. This is how we cultivate mindfulness.", topic: "mindfulness", author: "Jon Kabat-Zinn" },
  { text: "Mindfulness isn't difficult, we just need to remember to do it.", topic: "mindfulness", author: "Sharon Salzberg" },
  { text: "Suffering usually relates to wanting things to be different than they are.", topic: "mindfulness", author: "Allan Lokos" },
  { text: "Mindfulness is a way of befriending ourselves and our experience.", topic: "mindfulness", author: "Jon Kabat-Zinn" },
  { text: "The greatest prayer is patience.", topic: "mindfulness", author: "Buddha" },
  { text: "Smile, breathe, and go slowly.", topic: "mindfulness", author: "Thich Nhat Hanh" },

  // --- Happiness ---
  { text: "Happiness is when what you think, what you say, and what you do are in harmony.", topic: "happiness", author: "Mahatma Gandhi" },
  { text: "The purpose of our lives is to be happy.", topic: "happiness", author: "Dalai Lama" },
  { text: "Happiness depends upon ourselves.", topic: "happiness", author: "Aristotle" },
  { text: "For every minute you are angry you lose sixty seconds of happiness.", topic: "happiness", author: "Ralph Waldo Emerson" },
  { text: "Happiness is not something ready made. It comes from your own actions.", topic: "happiness", author: "Dalai Lama" },
  { text: "Think of all the beauty still left around you and be happy.", topic: "happiness", author: "Anne Frank" },
  { text: "Happiness is letting go of what you think your life is supposed to look like and embracing it for everything that it is.", topic: "happiness" },
  { text: "The most important thing is to enjoy your life—to be happy—it's all that matters.", topic: "happiness", author: "Audrey Hepburn" },
  { text: "Count your age by friends, not years. Count your life by smiles, not tears.", topic: "happiness", author: "John Lennon" },
  { text: "Happiness is a warm puppy.", topic: "happiness", author: "Charles M. Schulz" },
  { text: "Happiness is only real when shared.", topic: "happiness", author: "Jon Krakauer" },
  { text: "The only joy in the world is to begin.", topic: "happiness", author: "Cesare Pavese" },

  // --- Confidence ---
  { text: "Believe you can and you're halfway there.", topic: "confidence", author: "Theodore Roosevelt" },
  { text: "You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face.", topic: "confidence", author: "Eleanor Roosevelt" },
  { text: "The way to develop self-confidence is to do the thing you fear and get a record of successful experiences behind you.", topic: "confidence", author: "William Jennings Bryan" },
  { text: "Confidence comes not from always being right but from not fearing to be wrong.", topic: "confidence", author: "Peter T. Mcintyre" },
  { text: "Don't wait until everything is just right. It will never be perfect. There will always be challenges, obstacles, and less than perfect conditions. So what? Get started now.", topic: "confidence", author: "Mark Victor Hansen" },
  { text: "You are braver than you believe, stronger than you seem, and smarter than you think.", topic: "confidence", author: "A.A. Milne" },
  { text: "No one can make you feel inferior without your consent.", topic: "confidence", author: "Eleanor Roosevelt" },
  { text: "Confidence is not 'they will like me.' Confidence is 'I'll be fine if they don't.'", topic: "confidence", author: "Christina Grimmie" },
  { text: "The moment you doubt whether you can fly, you cease forever to be able to do it.", topic: "confidence", author: "J.M. Barrie" },
  { text: "With confidence, you have won before you have started.", topic: "confidence", author: "Marcus Garvey" },
  { text: "Always be yourself and have faith in yourself. Do not go out and look for a successful personality and try to duplicate it.", topic: "confidence", author: "Bruce Lee" },
  { text: "Trust yourself. You know more than you think you do.", topic: "confidence", author: "Benjamin Spock" },

  // --- Leadership ---
  { text: "A leader is one who knows the way, goes the way, and shows the way.", topic: "leadership", author: "John C. Maxwell" },
  { text: "The greatest leader is not necessarily the one who does the greatest things. He is the one that gets the people to do the greatest things.", topic: "leadership", author: "Ronald Reagan" },
  { text: "Leadership is not about being in charge. It is about taking care of those in your charge.", topic: "leadership", author: "Simon Sinek" },
  { text: "To handle yourself, use your head; to handle others, use your heart.", topic: "leadership", author: "Eleanor Roosevelt" },
  { text: "The function of leadership is to produce more leaders, not more followers.", topic: "leadership", author: "Ralph Nader" },
  { text: "A good leader takes a little more than his share of the blame, a little less than his share of the credit.", topic: "leadership", author: "Arnold H. Glasow" },
  { text: "Leadership is the capacity to translate vision into reality.", topic: "leadership", author: "Warren Bennis" },
  { text: "The best executive is the one who has sense enough to pick good men to do what he wants done, and self-restraint enough to keep from meddling with them while they do it.", topic: "leadership", author: "Theodore Roosevelt" },
  { text: "If your actions inspire others to dream more, learn more, do more and become more, you are a leader.", topic: "leadership", author: "John Quincy Adams" },
  { text: "Leadership does not always wear the harness of compromise.", topic: "leadership", author: "Woodrow Wilson" },
  { text: "The art of leadership is saying no, not saying yes. It is very easy to say yes.", topic: "leadership", author: "Tony Blair" },
  { text: "A leader is best when people barely know he exists, when his work is done, his aim fulfilled, they will say: we did it ourselves.", topic: "leadership", author: "Lao Tzu" },

  // --- Wisdom ---
  { text: "The only true wisdom is in knowing you know nothing.", topic: "wisdom", author: "Socrates" },
  { text: "Turn your wounds into wisdom.", topic: "wisdom", author: "Oprah Winfrey" },
  { text: "Knowledge speaks, but wisdom listens.", topic: "wisdom", author: "Jimi Hendrix" },
  { text: "The fool doth think he is wise, but the wise man knows himself to be a fool.", topic: "wisdom", author: "William Shakespeare" },
  { text: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", topic: "wisdom", author: "Albert Einstein" },
  { text: "The invariable mark of wisdom is to see the miraculous in the common.", topic: "wisdom", author: "Ralph Waldo Emerson" },
  { text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", topic: "wisdom", author: "Aristotle" },
  { text: "Wisdom begins in wonder.", topic: "wisdom", author: "Socrates" },
  { text: "The beginning of wisdom is the discovery of the meaning of things.", topic: "wisdom", author: "Plato" },
  { text: "Wisdom is the reward you get for a lifetime of listening when you'd have preferred to talk.", topic: "wisdom", author: "Doug Larson" },
  { text: "The greatest wisdom is in simplicity. Love, respect, compassion, kindness, and listening are more powerful than intelligence alone.", topic: "wisdom", author: "Leo Tolstoy" },
  { text: "We don't receive wisdom; we must discover it for ourselves after a journey that no one can take for us or spare us.", topic: "wisdom", author: "Marcel Proust" },

  // --- Friendship ---
  { text: "A friend is one who knows you as you are, understands where you have been, accepts what you have become, and still, gently allows you to grow.", topic: "friendship", author: "William Shakespeare" },
  { text: "Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one.'", topic: "friendship", author: "C.S. Lewis" },
  { text: "A true friend is someone who is there for you when he'd rather be anywhere else.", topic: "friendship", author: "Len Wein" },
  { text: "Friendship is the only cement that will ever hold the world together.", topic: "friendship", author: "Woodrow Wilson" },
  { text: "A real friend is one who walks in when the rest of the world walks out.", topic: "friendship", author: "Walter Winchell" },
  { text: "Friendship is not something you learn in school. But if you haven't learned the meaning of friendship, you really haven't learned anything.", topic: "friendship", author: "Muhammad Ali" },
  { text: "There is nothing on this earth more to be prized than true friendship.", topic: "friendship", author: "Thomas Aquinas" },
  { text: "My best friend is the one who brings out the best in me.", topic: "friendship", author: "Henry Ford" },
  { text: "Friendship is a single soul dwelling in two bodies.", topic: "friendship", author: "Aristotle" },
  { text: "True friendship comes when the silence between two people is comfortable.", topic: "friendship", author: "David Tyson Gentry" },
  { text: "A friend is someone who gives you total freedom to be yourself.", topic: "friendship", author: "Jim Morrison" },
  { text: "Friendship is always a sweet responsibility, never an opportunity.", topic: "friendship", author: "Kahlil Gibran" },

  // --- Life ---
  { text: "Life is what happens when you're busy making other plans.", topic: "life", author: "John Lennon" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", topic: "life", author: "Ralph Waldo Emerson" },
  { text: "Life is either a daring adventure or nothing at all.", topic: "life", author: "Helen Keller" },
  { text: "In three words I can sum up everything I've learned about life: it goes on.", topic: "life", author: "Robert Frost" },
  { text: "Life is really simple, but we insist on making it complicated.", topic: "life", author: "Confucius" },
  { text: "The unexamined life is not worth living.", topic: "life", author: "Socrates" },
  { text: "Life is not a problem to be solved, but a reality to be experienced.", topic: "life", author: "Søren Kierkegaard" },
  { text: "The biggest adventure you can take is to live the life of your dreams.", topic: "life", author: "Oprah Winfrey" },
  { text: "Life is a journey, not a destination.", topic: "life", author: "Ralph Waldo Emerson" },
  { text: "We must let go of the life we have planned, so as to accept the one that is waiting for us.", topic: "life", author: "Joseph Campbell" },
  { text: "Life shrinks or expands in proportion to one's courage.", topic: "life", author: "Anaïs Nin" },
  { text: "The purpose of life is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience.", topic: "life", author: "Eleanor Roosevelt" },
    
  // --- Courage ---
    { text: "Courage is not the absence of fear, but the triumph over it.", topic: "courage", author: "Nelson Mandela" },
    { text: "It takes courage to grow up and become who you really are.", topic: "courage", author: "E.E. Cummings" },
    { text: "You cannot swim for new horizons until you have courage to lose sight of the shore.", topic: "courage", author: "William Faulkner" },
    { text: "Courage is resistance to fear, mastery of fear, not absence of fear.", topic: "courage", author: "Mark Twain" },
    { text: "The only thing we have to fear is fear itself.", topic: "courage", author: "Franklin D. Roosevelt" },
    { text: "Courage is being scared to death, but saddling up anyway.", topic: "courage", author: "John Wayne" },
    { text: "Life shrinks or expands in proportion to one's courage.", topic: "courage", author: "Anaïs Nin" },
    { text: "Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.", topic: "courage", author: "Winston Churchill" },
    { text: "I learned that courage was not the absence of fear, but the triumph over it.", topic: "courage", author: "Nelson Mandela" },
    { text: "Success is not the absence of obstacles, but the courage to push through them.", topic: "courage", author: "Josh Shipp" },
    { text: "Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.'", topic: "courage", author: "Mary Anne Radmacher" },
    { text: "Have the courage to follow your heart and intuition. They somehow already know what you truly want to become.", topic: "courage", author: "Steve Jobs" },
  
    // --- Perseverance ---
    { text: "It does not matter how slowly you go as long as you do not stop.", topic: "perseverance", author: "Confucius" },
    { text: "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.", topic: "perseverance", author: "Vince Lombardi" },
    { text: "Perseverance is not a long race; it is many short races one after the other.", topic: "perseverance", author: "Walter Elliot" },
    { text: "Success is not the absence of obstacles, but the courage to push through them.", topic: "perseverance", author: "Josh Shipp" },
    { text: "Fall seven times, stand up eight.", topic: "perseverance", author: "Japanese Proverb" },
    { text: "Our greatest glory is not in never falling, but in rising every time we fall.", topic: "perseverance", author: "Confucius" },
    { text: "The only limit to our realization of tomorrow will be our doubts of today.", topic: "perseverance", author: "Franklin D. Roosevelt" },
    { text: "Perseverance is failing 19 times and succeeding the 20th.", topic: "perseverance", author: "Julie Andrews" },
    { text: "Many of life's failures are people who did not realize how close they were to success when they gave up.", topic: "perseverance", author: "Thomas Edison" },
    { text: "Keep on going, and the chances are that you will stumble on something, perhaps when you are least expecting it.", topic: "perseverance", author: "Charles F. Kettering" },
    { text: "Success seems to be largely a matter of hanging on after others have let go.", topic: "perseverance", author: "William Feather" },
    { text: "When you get to the end of your rope, tie a knot and hang on.", topic: "perseverance", author: "Franklin D. Roosevelt" },
  
    // --- Gratitude ---
    { text: "Gratitude makes sense of our past, brings peace for today, and creates a vision for tomorrow.", topic: "gratitude", author: "Melody Beattie" },
    { text: "As we express our gratitude, we must never forget that the highest appreciation is not to utter words, but to live by them.", topic: "gratitude", author: "John F. Kennedy" },
    { text: "Gratitude is not only the greatest of virtues, but the parent of all others.", topic: "gratitude", author: "Cicero" },
    { text: "Acknowledging the good that you already have in your life is the foundation for all abundance.", topic: "gratitude", author: "Eckhart Толле" },
    { text: "The root of joy is gratefulness.", topic: "gratitude", author: "David Steindl-Rast" },
    { text: "Gratitude turns what we have into enough.", topic: "gratitude", author: "Aesop" },
    { text: "When I started counting my blessings, my whole life turned around.", topic: "gratitude", author: "Willie Nelson" },
    { text: "Be thankful for what you have; you'll end up having more.", topic: "gratitude", author: "Oprah Winfrey" },
    { text: "Gratitude is a powerful catalyst for happiness. It's the spark that lights a fire of joy in your soul.", topic: "gratitude", author: "Amy Collette" },
    { text: "Feeling gratitude and not expressing it is like wrapping a present and not giving it.", topic: "gratitude", author: "William Arthur Ward" },
    { text: "The more grateful I am, the more beauty I see.", topic: "gratitude", author: "Mary Davis" },
    { text: "Gratitude is the fairest blossom which springs from the soul.", topic: "gratitude", author: "Henry Ward Beecher" },
  
    // --- Change ---
    { text: "The only way to make sense out of change is to plunge into it, move with it, and join the dance.", topic: "change", author: "Alan Watts" },
    { text: "Change is the law of life. And those who look only to the past or present are certain to miss the future.", topic: "change", author: "John F. Kennedy" },
    { text: "You must be the change you wish to see in the world.", topic: "change", author: "Mahatma Gandhi" },
    { text: "The greatest discovery of all time is that a person can change his future by merely changing his attitude.", topic: "change", author: "Oprah Winfrey" },
    { text: "Life is about not knowing, having to change, taking the moment and making the best of it.", topic: "change", author: "Gilda Radner" },
    { text: "To improve is to change; to be perfect is to change often.", topic: "change", author: "Winston Churchill" },
    { text: "Everyone thinks of changing the world, but no one thinks of changing himself.", topic: "change", author: "Leo Tolstoy" },
    { text: "Change your thoughts and you change your world.", topic: "change", author: "Norman Vincent Peale" },
    { text: "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.", topic: "change", author: "Albert Einstein" },
    { text: "They always say time changes things, but you actually have to change them yourself.", topic: "change", author: "Andy Warhol" },
    { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", topic: "change", author: "George Bernard Shaw" },
    { text: "When we are no longer able to change a situation, we are challenged to change ourselves.", topic: "change", author: "Viktor E. Frankl" },
  
    // --- Creativity ---
    { text: "Creativity is intelligence having fun.", topic: "creativity", author: "Albert Einstein" },
    { text: "You can't use up creativity. The more you use, the more you have.", topic: "creativity", author: "Maya Angelou" },
    { text: "To practice any art, no matter how well or badly, is a way to make your soul grow. So do it.", topic: "creativity", author: "Kurt Vonnegut" },
    { text: "Creativity doesn't wait for that perfect moment. It fashions its own perfect moments out of ordinary ones.", topic: "creativity", author: "Bruce Garrabrandt" },
    { text: "Imagination is everything. It is the preview of life's coming attractions.", topic: "creativity", author: "Albert Einstein" },
    { text: "The desire to create is one of the deepest yearnings of the human soul.", topic: "creativity", author: "Dieter F. Uchtdorf" },
    { text: "Creativity is seeing what others see and thinking what no one else ever thought.", topic: "creativity", author: "Albert Einstein" },
    { text: "You can't wait for inspiration. You have to go after it with a club.", topic: "creativity", author: "Jack London" },
    { text: "Creativity is the power to connect the seemingly unconnected.", topic: "creativity", author: "William Plomer" },
    { text: "The creative adult is the child who survived.", topic: "creativity", author: "Ursula K. Le Guin" },
    { text: "Creativity is allowing yourself to make mistakes. Art is knowing which ones to keep.", topic: "creativity", author: "Scott Adams" },
    { text: "Every child is an artist. The problem is how to remain an artist once we grow up.", topic: "creativity", author: "Pablo Picasso" },
  
    // --- Kindness ---
    { text: "No act of kindness, no matter how small, is ever wasted.", topic: "kindness", author: "Aesop" },
    { text: "Kindness is a language which the deaf can hear and the blind can see.", topic: "kindness", author: "Mark Twain" },
    { text: "You can accomplish by kindness what you cannot by force.", topic: "kindness", author: "Publilius Syrus" },
    { text: "Kindness in words creates confidence. Kindness in thinking creates profoundness. Kindness in giving creates love.", topic: "kindness", author: "Lao Tzu" },
    { text: "A warm smile is the universal language of kindness.", topic: "kindness", author: "William Arthur Ward" },
    { text: "The smallest act of kindness is worth more than the grandest intention.", topic: "kindness", author: "Oscar Wilde" },
    { text: "Kindness is the sunshine in which virtue grows.", topic: "kindness", author: "Robert Green Ingersoll" },
    { text: "Be kind, for everyone you meet is fighting a harder battle.", topic: "kindness", author: "Plato" },
    { text: "Carry out a random act of kindness, with no expectation of reward.", topic: "kindness", author: "Princess Diana" },
    { text: "Kindness is the golden chain by which society is bound together.", topic: "kindness", author: "Johann Wolfgang von Goethe" },
    { text: "Kind words can be short and easy to speak, but their echoes are truly endless.", topic: "kindness", author: "Mother Teresa" },
    { text: "Wherever there is a human being, there is an opportunity for a kindness.", topic: "kindness", author: "Seneca" },
  
    // --- Hope ---
    { text: "Hope is the thing with feathers that perches in the soul.", topic: "hope", author: "Emily Dickinson" },
    { text: "We must accept finite disappointment, but never lose infinite hope.", topic: "hope", author: "Martin Luther King Jr." },
    { text: "Hope is being able to see that there is light despite all of the darkness.", topic: "hope", author: "Desmond Tutu" },
    { text: "While there's life, there's hope.", topic: "hope", author: "Cicero" },
    { text: "Hope is a waking dream.", topic: "hope", author: "Aristotle" },
    { text: "Once you choose hope, anything's possible.", topic: "hope", author: "Christopher Reeve" },
    { text: "Hope smiles from the threshold of the year to come, whispering, 'It will be happier.'", topic: "hope", author: "Alfred Lord Tennyson" },
    { text: "Hope is the companion of power, and the mother of success.", topic: "hope", author: "Samuel Smiles" },
    { text: "The very least you can do in your life is figure out what you hope for.", topic: "hope", author: "Barbara Kingsolver" },
    { text: "Hope is the dream of a waking man.", topic: "hope", author: "Plato" },
    { text: "In all things it is better to hope than to despair.", topic: "hope", author: "Johann Wolfgang von Goethe" },
    { text: "Hope is the only thing stronger than fear.", topic: "hope", author: "Suzanne Collins" },
  
    // --- Freedom ---
    { text: "Freedom is not worth having if it does not include the freedom to make mistakes.", topic: "freedom", author: "Mahatma Gandhi" },
    { text: "The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.", topic: "freedom", author: "Albert Camus" },
    { text: "Freedom lies in being bold.", topic: "freedom", author: "Robert Frost" },
    { text: "Those who deny freedom to others deserve it not for themselves.", topic: "freedom", author: "Abraham Lincoln" },
    { text: "For to be free is not merely to cast off one's chains, but to live in a way that respects and enhances the freedom of others.", topic: "freedom", author: "Nelson Mandela" },
    { text: "Freedom is the oxygen of the soul.", topic: "freedom", author: "Moshe Dayan" },
    { text: "The secret of happiness is freedom, and the secret of freedom, courage.", topic: "freedom", author: "Thucydides" },
    { text: "Liberty, when it begins to take root, is a plant of rapid growth.", topic: "freedom", author: "George Washington" },
    { text: "Freedom is nothing but a chance to be better.", topic: "freedom", author: "Albert Camus" },
    { text: "The most courageous act is still to think for yourself. Aloud.", topic: "freedom", author: "Coco Chanel" },
    { text: "Freedom is the open window through which pours the sunlight of the human spirit and human dignity.", topic: "freedom", author: "Herbert Hoover" },
    { text: "They who can give up essential liberty to obtain a little temporary safety deserve neither liberty nor safety.", topic: "freedom", author: "Benjamin Franklin" },
  
    // --- Passion ---
    { text: "Follow your passion, it will lead you to your purpose.", topic: "passion", author: "Oprah Winfrey" },
    { text: "Passion is energy. Feel the power that comes from focusing on what excites you.", topic: "passion", author: "Oprah Winfrey" },
    { text: "There is no passion to be found playing small—in settling for a life that is less than the one you are capable of living.", topic: "passion", author: "Nelson Mandela" },
    { text: "Passion is the genesis of genius.", topic: "passion", author: "Tony Robbins" },
    { text: "If you don't love what you do, you won't do it with much conviction or passion.", topic: "passion", author: "Mia Hamm" },
    { text: "Passion is the oxygen of the soul.", topic: "passion", author: "Bill Hawkins" },
    { text: "Don't ask yourself what the world needs. Ask what makes you come Alive, and then go do it.", topic: "passion", author: "Howard Thurman" },
    { text: "Nothing great in the world has ever been accomplished without passion.", topic: "passion", author: "Georg Wilhelm Friedrich Hegel" },
    { text: "Passion will move men beyond themselves, beyond their shortcomings, beyond their failures.", topic: "passion", author: "Joseph Campbell" },
    { text: "Passion rebuilds the world for the better. It is the spark of all change.", topic: "passion", author: "Carl Gustav Jung" },
    { text: "The only way to do great work is to love what you do.", topic: "passion", author: "Steve Jobs" },
    { text: "Passion is the spark that ignites purpose and fuels progress.", topic: "passion", author: "Denis Waitley" },
  
    // --- Resilience ---
    { text: "The oak fought the wind and was broken, the willow bent when it must and survived.", topic: "resilience", author: "Robert Jordan" },
    { text: "You may have to fight a battle more than once to win it.", topic: "resilience", author: "Margaret Thatcher" },
    { text: "Resilience is not about never falling, but about rising every time you do.", topic: "resilience", author: "Vince Lombardi" },
    { text: "The human capacity for burden is like bamboo—far more flexible than you'd ever believe at first glance.", topic: "resilience", author: "Jodi Picoult" },
    { text: "We don't develop courage by being happy every day. We develop it by surviving difficult times and challenging adversity.", topic: "resilience", author: "Barbara De Angelis" },
    { text: "Resilience is knowing that you are the only one that has the power and the responsibility to pick yourself up.", topic: "resilience", author: "Mary Holloway" },
    { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", topic: "resilience", author: "Nelson Mandela" },
    { text: "Resilience is the ability to attack while still learning.", topic: "resilience", author: "John C. Maxwell" },
    { text: "What does not destroy me, makes me stronger.", topic: "resilience", author: "Friedrich Nietzsche" },
    { text: "Difficulties are meant to rouse, not discourage. The human spirit is to grow strong by conflict.", topic: "resilience", author: "William Ellery Channing" },
    { text: "Resilience is accepting your new reality, even if it's less good than the one you had before.", topic: "resilience", author: "Elizabeth Edwards" },
    { text: "The bend in the road is not the end of the road… unless you fail to make the turn.", topic: "resilience", author: "Helen Keller" },

  
  // --- Determination ---
  { text: "The difference between the impossible and the possible lies in a person's determination.", topic: "determination", author: "Tommy Lasorda" },
  { text: "A dream doesn't become reality through magic; it takes sweat, determination and hard work.", topic: "determination", author: "Colin Powell" },
  { text: "Determination gives you the resolve to keep going in spite of the roadblocks that lay before you.", topic: "determination", author: "Denis Waitley" },
  { text: "The price of success is hard work, dedication to the job at hand, and the determination that whether we win or lose, we have applied the best of ourselves to the task at hand.", topic: "determination", author: "Vince Lombardi" },
  { text: "It's not about the size of the dog in the fight, but the size of the fight in the dog.", topic: "determination", author: "Mark Twain" },
  { text: "You've got to get up every morning with determination if you're going to go to bed with satisfaction.", topic: "determination", author: "George Lorimer" },
  { text: "Failure will never overtake me if my determination to succeed is strong enough.", topic: "determination", author: "Og Mandino" },
  { text: "Determination is the wake-up call to the human will.", topic: "determination", author: "Anthony Robbins" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today. Let us move forward with strong and active determination.", topic: "determination", author: "Franklin D. Roosevelt" },
  { text: "Nothing in this world can take the place of persistence. Talent will not; nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. Education will not; the world is full of educated derelicts. Persistence and determination alone are omnipotent.", topic: "determination", author: "Calvin Coolidge" },
  { text: "The man who can drive himself further once the effort gets painful is the man who will win.", topic: "determination", author: "Roger Bannister" },
  { text: "Determination becomes obsession and then it becomes all that matters.", topic: "determination", author: "Jeremy Irvine" },

  // --- Integrity ---
  { text: "Integrity is doing the right thing, even when no one is watching.", topic: "integrity", author: "C.S. Lewis" },
  { text: "Honesty is the first chapter in the book of wisdom.", topic: "integrity", author: "Thomas Jefferson" },
  { text: "The time is always right to do what is right.", topic: "integrity", author: "Martin Luther King Jr." },
  { text: "Integrity is the essence of everything successful.", topic: "integrity", author: "R. Buckminster Fuller" },
  { text: "Real integrity is doing the right thing, knowing that nobody's going to know whether you did it or not.", topic: "integrity", author: "Oprah Winfrey" },
  { text: "The strength of a nation derives from the integrity of the home.", topic: "integrity", author: "Confucius" },
  { text: "Integrity is not something you show others. It is how you behave behind their back.", topic: "integrity", author: "Anonymous" },
  { text: "Whoever is careless with the truth in small matters cannot be trusted with important matters.", topic: "integrity", author: "Albert Einstein" },
  { text: "In matters of style, swim with the current; in matters of principle, stand like a rock.", topic: "integrity", author: "Thomas Jefferson" },
  { text: "Integrity is choosing your thoughts and actions based on values rather than personal gain.", topic: "integrity", author: "Chris Karcher" },
  { text: "The supreme quality for leadership is unquestionably integrity.", topic: "integrity", author: "Dwight D. Eisenhower" },
  { text: "Have the courage to say no. Have the courage to face the truth. Do the right thing because it is right. These are the magic keys to living your life with integrity.", topic: "integrity", author: "W. Clement Stone" },

  // --- Compassion ---
  { text: "Compassion is the basis of morality.", topic: "compassion", author: "Arthur Schopenhauer" },
  { text: "If you want others to be happy, practice compassion. If you want to be happy, practice compassion.", topic: "compassion", author: "Dalai Lama" },
  { text: "The purpose of human life is to serve, and to show compassion and the will to help others.", topic: "compassion", author: "Albert Schweitzer" },
  { text: "Compassion is not just feeling with someone, but seeking to change the situation.", topic: "compassion", author: "Desmond Tutu" },
  { text: "Love and compassion are necessities, not luxuries. Without them, humanity cannot survive.", topic: "compassion", author: "Dalai Lama" },
  { text: "A kind gesture can reach a wound that only compassion can heal.", topic: "compassion", author: "Steve Maraboli" },
  { text: "Compassion is the keen awareness of the interdependence of all things.", topic: "compassion", author: "Thomas Merton" },
  { text: "Compassion is a verb.", topic: "compassion", author: "Thich Nhat Hanh" },
  { text: "We can't heal the world today, but we can begin with a voice of compassion.", topic: "compassion", author: "Deepak Chopra" },
  { text: "Compassion is the wish to see others free from suffering.", topic: "compassion", author: "Dalai Lama" },
  { text: "The only way out of the labyrinth of suffering is to forgive.", topic: "compassion", author: "John Green" },
  { text: "Compassion brings us to a stop, and for a moment we rise above ourselves.", topic: "compassion", author: "Mason Cooley" },

  // --- Adventure ---
  { text: "Life is either a daring adventure or nothing at all.", topic: "adventure", author: "Helen Keller" },
  { text: "The biggest adventure you can take is to live the life of your dreams.", topic: "adventure", author: "Oprah Winfrey" },
  { text: "Adventure is worthwhile in itself.", topic: "adventure", author: "Amelia Earhart" },
  { text: "The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.", topic: "adventure", author: "Marcel Proust" },
  { text: "Jobs fill your pockets, but adventures fill your soul.", topic: "adventure", author: "Jaime Lyn Beatty" },
  { text: "To travel is to live.", topic: "adventure", author: "Hans Christian Andersen" },
  { text: "Adventure is not outside man; it is within.", topic: "adventure", author: "George Eliot" },
  { text: "The world is full of magic things, patiently waiting for our senses to grow sharper.", topic: "adventure", author: "W.B. Yeats" },
  { text: "Life is an adventure, it's not a package tour.", topic: "adventure", author: "Eckhart Tolle" },
  { text: "The journey not the arrival matters.", topic: "adventure", author: "T.S. Eliot" },
  { text: "Adventure may hurt you, but monotony will kill you.", topic: "adventure", author: "Anonymous" },
  { text: "We live in a wonderful world that is full of beauty, charm, and adventure.", topic: "adventure", author: "Jawaharlal Nehru" },

  // --- Purpose ---
  { text: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", topic: "purpose", author: "Ralph Waldo Emerson" },
  { text: "The meaning of life is to find your gift. The purpose of life is to give it away.", topic: "purpose", author: "Pablo Picasso" },
  { text: "People take different roads seeking fulfillment and happiness. Just because they're not on your road doesn't mean they've gotten lost.", topic: "purpose", author: "Dalai Lama" },
  { text: "Your purpose in life is to find your purpose and give your whole heart and soul to it.", topic: "purpose", author: "Buddha" },
  { text: "The two most important days in your life are the day you are born and the day you find out why.", topic: "purpose", author: "Mark Twain" },
  { text: "Efforts and courage are not enough without purpose and direction.", topic: "purpose", author: "John F. Kennedy" },
  { text: "The mystery of human existence lies not in just staying alive, but in finding something to live for.", topic: "purpose", author: "Fyodor Dostoevsky" },
  { text: "He who has a why to live can bear almost any how.", topic: "purpose", author: "Friedrich Nietzsche" },
  { text: "The purpose of life is a life of purpose.", topic: "purpose", author: "Robert Byrne" },
  { text: "You were born with a purpose, and the universe is conspiring to help you find it.", topic: "purpose", author: "Ralph Waldo Emerson" },
  { text: "Purpose is the reason you journey. Passion is the fire that lights your way.", topic: "purpose", author: "Josh Shipp" },
  { text: "The heart of human excellence often begins to beat when you discover a pursuit that absorbs you, frees you, challenges you, or gives you a sense of meaning.", topic: "purpose", author: "Mihaly Csikszentmihalyi" },

  // --- Optimism ---
  { text: "Keep your face always toward the sunshine—and shadows will fall behind you.", topic: "optimism", author: "Walt Whitman" },
  { text: "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.", topic: "optimism", author: "Helen Keller" },
  { text: "The optimist sees the rose and not its thorns; the pessimist stares at the thorns, oblivious to the rose.", topic: "optimism", author: "Kahlil Gibran" },
  { text: "Choose to be optimistic, it feels better.", topic: "optimism", author: "Dalai Lama" },
  { text: "An optimist is the human personification of spring.", topic: "optimism", author: "Susan J. Bissonette" },
  { text: "Optimism is a happiness magnet. If you stay positive, good things and good people will be drawn to you.", topic: "optimism", author: "Mary Lou Retton" },
  { text: "Instead of worrying about what you cannot control, shift your energy to what you can create.", topic: "optimism", author: "Roy T. Bennett" },
  { text: "The greatest discovery of my generation is that a human being can alter his life by altering his attitudes.", topic: "optimism", author: "William James" },
  { text: "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.", topic: "optimism", author: "Winston Churchill" },
  { text: "Optimism is the foundation of courage.", topic: "optimism", author: "Nicholas Murray Butler" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", topic: "optimism", author: "Marcus Aurelius" },
  { text: "Write it on your heart that every day is the best day in the year.", topic: "optimism", author: "Ralph Waldo Emerson" },

  // --- Trust ---
  { text: "Trust is the glue of life. It's the most essential ingredient in effective communication.", topic: "trust", author: "Stephen R. Covey" },
  { text: "He who does not trust enough will not be trusted.", topic: "trust", author: "Lao Tzu" },
  { text: "To be trusted is a greater compliment than being loved.", topic: "trust", author: "George MacDonald" },
  { text: "Trust is like the air we breathe—when it's present, nobody really notices; when it's absent, everybody notices.", topic: "trust", author: "Warren Buffett" },
  { text: "Trust is built with consistency.", topic: "trust", author: "Lincoln Chafee" },
  { text: "The best way to find out if you can trust somebody is to trust them.", topic: "trust", author: "Ernest Hemingway" },
  { text: "Trust is the highest form of human motivation.", topic: "trust", author: "Stephen R. Covey" },
  { text: "Trust starts with truth and ends with truth.", topic: "trust", author: "Santosh Kalwar" },
  { text: "Trust is earned when actions meet words.", topic: "trust", author: "Chris Butler" },
  { text: "Trust is the fruit of a relationship in which you know you are loved.", topic: "trust", author: "William Paul Young" },
  { text: "Trust is like a mirror, you can fix it if it's broken, but you can still see the crack in the reflection.", topic: "trust", author: "Lady Gaga" },
  { text: "Whoever is careless with the truth in small matters cannot be trusted with important matters.", topic: "trust", author: "Albert Einstein" },

  // --- Growth ---
  { text: "We can't become what we need to be by remaining what we are.", topic: "growth", author: "Oprah Winfrey" },
  { text: "The only way that we can live, is if we grow. The only way that we can grow is if we change.", topic: "growth", author: "C. JoyBell C." },
  { text: "Growth is the only evidence of life.", topic: "growth", author: "John Henry Newman" },
  { text: "The key to growth is the introduction of higher dimensions of consciousness into our awareness.", topic: "growth", author: "Lao Tzu" },
  { text: "Personal growth is not a matter of learning new information but of unlearning old limits.", topic: "growth", author: "Alan Cohen" },
  { text: "Life is growth. If we stop growing, technically and spiritually, we are as good as dead.", topic: "growth", author: "Morihei Ueshiba" },
  { text: "The greatest thing in the world is to know how to belong to oneself.", topic: "growth", author: "Michel de Montaigne" },
  { text: "Growth demands a temporary surrender of security.", topic: "growth", author: "Gail Sheehy" },
  { text: "We don't grow when things are easy; we grow when we face challenges.", topic: "growth", author: "Joyce Meyer" },
  { text: "The journey of growth is a lifelong adventure.", topic: "growth", author: "John C. Maxwell" },
  { text: "Growth is painful. Change is painful. But nothing is as painful as staying stuck somewhere you don't belong.", topic: "growth", author: "Mandy Hale" },
  { text: "Strength and growth come only through continuous effort and struggle.", topic: "growth", author: "Napoleon Hill" },

  // --- Peace ---
  { text: "Peace begins with a smile.", topic: "peace", author: "Mother Teresa" },
  { text: "When the power of love overcomes the love of power, the world will know peace.", topic: "peace", author: "Jimi Hendrix" },
  { text: "Peace is not absence of conflict, it is the ability to handle conflict by peaceful means.", topic: "peace", author: "Ronald Reagan" },
  { text: "If we have no peace, it is because we have forgotten that we belong to each other.", topic: "peace", author: "Mother Teresa" },
  { text: "Peace cannot be kept by force; it can only be achieved by understanding.", topic: "peace", author: "Albert Einstein" },
  { text: "Peace is the beauty of life. It is sunshine. It is the smile of a child, the love of a mother, the joy of a father, the togetherness of a family.", topic: "peace", author: "Menachem Begin" },
  { text: "Peace is a journey of a thousand miles and it must be taken one step at a time.", topic: "peace", author: "Lyndon B. Johnson" },
  { text: "You cannot find peace by avoiding life.", topic: "peace", author: "Virginia Woolf" },
  { text: "Peace is not something you wish for; it's something you make, something you do, something you are, and something you give away.", topic: "peace", author: "John Lennon" },
  { text: "The practice of peace and reconciliation is one of the most vital and artistic of human actions.", topic: "peace", author: "Thich Nhat Hanh" },
  { text: "Peace is always beautiful.", topic: "peace", author: "Walt Whitman" },
  { text: "There is no way to peace; peace is the way.", topic: "peace", author: "A.J. Muste" },

  // --- Faith ---
  { text: "Faith is taking the first step even when you don't see the whole staircase.", topic: "faith", author: "Martin Luther King Jr." },
  { text: "Faith is the bird that feels the light when the dawn is still dark.", topic: "faith", author: "Rabindranath Tagore" },
  { text: "Faith is not belief without proof, but trust without reservation.", topic: "faith", author: "D. Elton Trueblood" },
  { text: "To have faith is to trust yourself to the water. When you swim you don't grab hold of the water, because if you do you will sink and drown. Instead you relax, and float.", topic: "faith", author: "Alan Watts" },
  { text: "Faith is the strength by which a shattered world shall emerge into the light.", topic: "faith", author: "Helen Keller" },
  { text: "Faith is to believe what you do not see; the reward of this faith is to see what you believe.", topic: "faith", author: "Saint Augustine" },
  { text: "Sometimes your only available transportation is a leap of faith.", topic: "faith", author: "Margaret Shepard" },
  { text: "Faith is not the belief that God will do what you want. It is the belief that God will do what is right.", topic: "faith", author: "Max Lucado" },
  { text: "Faith is the art of holding on to things in spite of your changing moods and circumstances.", topic: "faith", author: "C.S. Lewis" },
  { text: "Faith does not eliminate questions. But faith knows where to take them.", topic: "faith", author: "Elisabeth Elliot" },
  { text: "Faith is the daring of the soul to go farther than it can see.", topic: "faith", author: "William Newton Clarke" },
  { text: "You must not lose faith in humanity. Humanity is an ocean; if a few drops of the ocean are dirty, the ocean does not become dirty.", topic: "faith", author: "Mahatma Gandhi" },

  
  // --- Ambition ---
  { text: "Ambition is the path to success. Persistence is the vehicle you arrive in.", topic: "ambition", author: "Bill Bradley" },
  { text: "Keep away from those who try to belittle your ambitions. Small people always do that, but the really great make you believe that you too can become great.", topic: "ambition", author: "Mark Twain" },
  { text: "Ambition is enthusiasm with a purpose.", topic: "ambition", author: "Frank Tyger" },
  { text: "The starting point of all achievement is desire.", topic: "ambition", author: "Napoleon Hill" },
  { text: "Ambition is the first step to success. The second step is action.", topic: "ambition", author: "Anonymous" },
  { text: "Great ambition is the passion of a great character. Those endowed with it may perform very good or very bad acts. All depends on the principles which direct them.", topic: "ambition", author: "Napoleon Bonaparte" },
  { text: "Without ambition one starts nothing. Without work one finishes nothing.", topic: "ambition", author: "Ralph Waldo Emerson" },
  { text: "A man's worth is no greater than the worth of his ambitions.", topic: "ambition", author: "Marcus Aurelius" },
  { text: "Ambition is a dream with a V8 engine.", topic: "ambition", author: "Elvis Presley" },
  { text: "The ambitious are forever followed by adulation for they receive the most pleasure from flattery.", topic: "ambition", author: "Oliver Goldsmith" },
  { text: "To be ambitious is to be human; to achieve is to be divine.", topic: "ambition", author: "Anonymous" },
  { text: "Ambition is not a vice of little people.", topic: "ambition", author: "Michel de Montaigne" },

  // --- Balance ---
  { text: "Balance is not something you find, it's something you create.", topic: "balance", author: "Jana Kingsford" },
  { text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", topic: "balance", author: "Albert Einstein" },
  { text: "The best and safest thing is to keep a balance in your life, acknowledge the great powers around us and in us.", topic: "balance", author: "Euripides" },
  { text: "Happiness is not a matter of intensity but of balance, order, rhythm and harmony.", topic: "balance", author: "Thomas Merton" },
  { text: "You can't have everything you want, but you can have the things that really matter to you.", topic: "balance", author: "Marissa Mayer" },
  { text: "Balance is the key to everything. What we do, think, say, eat, feel, they all require awareness, and through this awareness we can grow.", topic: "balance", author: "Koi Fresco" },
  { text: "The calm and balanced mind is the strong and great mind; the hurried and agitated mind is the weak one.", topic: "balance", author: "Wallace D. Wattles" },
  { text: "Balance, peace, and joy are the fruit of a successful life. It starts with recognizing your talents and finding ways to serve others by using them.", topic: "balance", author: "Thomas Kinkade" },
  { text: "The foundation stones for a balanced success are honesty, character, integrity, faith, love and loyalty.", topic: "balance", author: "Zig Ziglar" },
  { text: "In all aspects of our lives, balance is key. Doing one thing too much can cause upset, like the old saying goes, everything in moderation is the secret.", topic: "balance", author: "Catherine Pulsifer" },
  { text: "Moderation is the silken string running through the pearl chain of all virtues.", topic: "balance", author: "Joseph Hall" },
  { text: "Balance is not better time management, but better boundary management.", topic: "balance", author: "Betsy Jacobson" },

  // --- Curiosity ---
  { text: "Curiosity is the wick in the candle of learning.", topic: "curiosity", author: "William Arthur Ward" },
  { text: "I have no special talents. I am only passionately curious.", topic: "curiosity", author: "Albert Einstein" },
  { text: "The important thing is not to stop questioning. Curiosity has its own reason for existing.", topic: "curiosity", author: "Albert Einstein" },
  { text: "Curiosity is one of the most permanent and certain characteristics of a vigorous intellect.", topic: "curiosity", author: "Samuel Johnson" },
  { text: "Curiosity is the engine of achievement.", topic: "curiosity", author: "Ken Robinson" },
  { text: "Curiosity does, no less than devotion, pilgrims make.", topic: "curiosity", author: "Abraham Cowley" },
  { text: "The cure for boredom is curiosity. There is no cure for curiosity.", topic: "curiosity", author: "Dorothy Parker" },
  { text: "Curiosity is, in great and generous minds, the first passion and the last.", topic: "curiosity", author: "Samuel Johnson" },
  { text: "Curiosity is the spark behind the spark of every great idea.", topic: "curiosity", author: "Anonymous" },
  { text: "The mind that opens to a new idea never returns to its original size.", topic: "curiosity", author: "Oliver Wendell Holmes" },
  { text: "Curiosity will conquer fear even more than bravery will.", topic: "curiosity", author: "James Stephens" },
  { text: "Curiosity is the lust of the mind.", topic: "curiosity", author: "Thomas Hobbes" },

  // --- Empathy ---
  { text: "Empathy is seeing with the eyes of another, listening with the ears of another, and feeling with the heart of another.", topic: "empathy", author: "Alfred Adler" },
  { text: "If you aren't impressed with the picture of the Sistine Chapel, you haven't stood under it. If you aren't impressed with the person next to you, you haven't listened to their story.", topic: "empathy", author: "Anonymous" },
  { text: "Empathy is about finding echoes of another person in yourself.", topic: "empathy", author: "Mohsin Hamid" },
  { text: "The great gift of human beings is that we have the power of empathy.", topic: "empathy", author: "Meryl Streep" },
  { text: "Empathy is the starting point for creating a community and taking action. It's the impetus for creating change.", topic: "empathy", author: "Max Carver" },
  { text: "You can only understand people if you feel them in yourself.", topic: "empathy", author: "John Steinbeck" },
  { text: "Empathy is simply listening, holding space, withholding judgment, emotionally connecting, and communicating that incredibly healing message of ‘You're not alone.'", topic: "empathy", author: "Brené Brown" },
  { text: "Empathy does not require you to agree; it requires you to understand.", topic: "empathy", author: "Anonymous" },
  { text: "Whenever you feel like criticizing anyone, just remember that all the people in this world haven't had the advantages that you've had.", topic: "empathy", author: "F. Scott Fitzgerald" },
  { text: "Empathy is the bridge that connects us to the hearts of others.", topic: "empathy", author: "Anonymous" },
  { text: "Learning to stand in somebody else's shoes, to see through their eyes, that's how peace begins.", topic: "empathy", author: "Barack Obama" },
  { text: "Empathy is the ability to step outside of your own bubble and into the bubbles of other people.", topic: "empathy", author: "C. JoyBell C." },

  // --- Forgiveness ---
  { text: "Forgiveness is the fragrance that the violet sheds on the heel that has crushed it.", topic: "forgiveness", author: "Mark Twain" },
  { text: "To forgive is to set a prisoner free and discover that the prisoner was you.", topic: "forgiveness", author: "Lewis B. Smedes" },
  { text: "The weak can never forgive. Forgiveness is the attribute of the strong.", topic: "forgiveness", author: "Mahatma Gandhi" },
  { text: "Forgiveness does not change the past, but it does enlarge the future.", topic: "forgiveness", author: "Paul Boese" },
  { text: "To err is human; to forgive, divine.", topic: "forgiveness", author: "Alexander Pope" },
  { text: "Forgiveness is not an occasional act; it is a constant attitude.", topic: "forgiveness", author: "Martin Luther King Jr." },
  { text: "Forgiveness is the key to action and freedom.", topic: "forgiveness", author: "Hannah Arendt" },
  { text: "We must develop and maintain the capacity to forgive. He who is devoid of the power to forgive is devoid of the power to love.", topic: "forgiveness", author: "Martin Luther King Jr." },
  { text: "Forgiveness is giving up the hope that the past could have been any different.", topic: "forgiveness", author: "Oprah Winfrey" },
  { text: "Forgiveness is the final form of love.", topic: "forgiveness", author: "Reinhold Niebuhr" },
  { text: "When you forgive, you in no way change the past—but you sure do change the future.", topic: "forgiveness", author: "Bernard Meltzer" },
  { text: "Forgiveness is a gift you give yourself.", topic: "forgiveness", author: "Tony Robbins" },

  // --- Honesty ---
  { text: "Honesty is the first chapter in the book of wisdom.", topic: "honesty", author: "Thomas Jefferson" },
  { text: "No legacy is so rich as honesty.", topic: "honesty", author: "William Shakespeare" },
  { text: "Honesty is the best policy.", topic: "honesty", author: "Benjamin Franklin" },
  { text: "The truth is rarely pure and never simple.", topic: "honesty", author: "Oscar Wilde" },
  { text: "Honesty is more than not lying. It is truth telling, truth speaking, truth living, and truth loving.", topic: "honesty", author: "James E. Faust" },
  { text: "To be honest, as this world goes, is to be one man picked out of ten thousand.", topic: "honesty", author: "William Shakespeare" },
  { text: "Honesty is the cornerstone of all success, without which confidence and ability to perform shall cease to exist.", topic: "honesty", author: "Mary Kay Ash" },
  { text: "Honesty does not always bring a response of love, but it is absolutely essential to it.", topic: "honesty", author: "Ray Blanton" },
  { text: "The truth will set you free, but first it will make you miserable.", topic: "honesty", author: "James A. Garfield" },
  { text: "Honesty is the fastest way to prevent a mistake from turning into a failure.", topic: "honesty", author: "James Altucher" },
  { text: "An honest man's the noblest work of God.", topic: "honesty", author: "Alexander Pope" },
  { text: "Honesty is a very expensive gift. Don't expect it from cheap people.", topic: "honesty", author: "Warren Buffett" },

  // --- Inspiration ---
  { text: "The best way to predict the future is to create it.", topic: "inspiration", author: "Peter Drucker" },
  { text: "You must be the change you wish to see in the world.", topic: "inspiration", author: "Mahatma Gandhi" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", topic: "inspiration", author: "Ralph Waldo Emerson" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", topic: "inspiration", author: "Franklin D. Roosevelt" },
  { text: "Do not wait to strike till the iron is hot; but make it hot by striking.", topic: "inspiration", author: "William Butler Yeats" },
  { text: "Inspiration does exist, but it must find you working.", topic: "inspiration", author: "Pablo Picasso" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", topic: "inspiration", author: "Eleanor Roosevelt" },
  { text: "You are never too old to set another goal or to dream a new dream.", topic: "inspiration", author: "C.S. Lewis" },
  { text: "The only way to do great work is to love what you do.", topic: "inspiration", author: "Steve Jobs" },
  { text: "Inspiration is a guest that does not willingly visit the idle.", topic: "inspiration", author: "Pyotr Ilyich Tchaikovsky" },
  { text: "If your actions inspire others to dream more, learn more, do more, and become more, you are a leader.", topic: "inspiration", author: "John Quincy Adams" },
  { text: "Don't ask what the world needs. Ask what makes you come alive, and go do it.", topic: "inspiration", author: "Howard Thurman" },

  // --- Joy ---
  { text: "Find ecstasy in life; the mere sense of living is joy enough.", topic: "joy", author: "Emily Dickinson" },
  { text: "Joy is not in things; it is in us.", topic: "joy", author: "Richard Wagner" },
  { text: "We cannot cure the world of sorrows, but we can choose to live in joy.", topic: "joy", author: "Joseph Campbell" },
  { text: "The healthiest response to life is joy.", topic: "joy", author: "Deepak Chopra" },
  { text: "Joy does not simply happen to us. We have to choose joy and keep choosing it every day.", topic: "joy", author: "Henri J.M. Nouwen" },
  { text: "The soul's joy lies in doing.", topic: "joy", author: "Percy Bysshe Shelley" },
  { text: "Happiness is a choice, but joy is a gift.", topic: "joy", author: "Anonymous" },
  { text: "Joy is the simplest form of gratitude.", topic: "joy", author: "Karl Barth" },
  { text: "A thing of beauty is a joy forever.", topic: "joy", author: "John Keats" },
  { text: "Joy is what happens to us when we allow ourselves to recognize how good things really are.", topic: "joy", author: "Marianne Williamson" },
  { text: "There are those who give with joy, and that joy is their reward.", topic: "joy", author: "Kahlil Gibran" },
  { text: "The joy we feel has little to do with the circumstances of our lives and everything to do with the focus of our lives.", topic: "joy", author: "Russell M. Nelson" },

  // --- Patience ---
  { text: "Patience is not the ability to wait, but the ability to keep a good attitude while waiting.", topic: "patience", author: "Joyce Meyer" },
  { text: "The greatest prayer is patience.", topic: "patience", author: "Buddha" },
  { text: "Patience, persistence and perspiration make an unbeatable combination for success.", topic: "patience", author: "Napoleon Hill" },
  { text: "Adopt the pace of nature: her secret is patience.", topic: "patience", author: "Ralph Waldo Emerson" },
  { text: "Patience is bitter, but its fruit is sweet.", topic: "patience", author: "Aristotle" },
  { text: "Patience is the companion of wisdom.", topic: "patience", author: "Saint Augustine" },
  { text: "All things come to him who waits—provided he knows what he is waiting for.", topic: "patience", author: "Woodrow Wilson" },
  { text: "Patience is the key to paradise.", topic: "patience", author: "Turkish Proverb" },
  { text: "With love and patience, nothing is impossible.", topic: "patience", author: "Daisaku Ikeda" },
  { text: "Patience is not passive; on the contrary, it is active; it is concentrated strength.", topic: "patience", author: "Edward G. Bulwer-Lytton" },
  { text: "The two most powerful warriors are patience and time.", topic: "patience", author: "Leo Tolstoy" },
  { text: "Patience is the art of hoping.", topic: "patience", author: "Luc de Clapiers" },

  // --- Strength ---
  { text: "That which does not kill us makes us stronger.", topic: "strength", author: "Friedrich Nietzsche" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", topic: "strength", author: "Mahatma Gandhi" },
  { text: "We acquire the strength we have overcome.", topic: "strength", author: "Ralph Waldo Emerson" },
  { text: "You have power over your mind—not outside events. Realize this, and you will find strength.", topic: "strength", author: "Marcus Aurelius" },
  { text: "Strength is the product of struggle; you must do what others don't to achieve what others won't.", topic: "strength", author: "Henry Rollins" },
  { text: "The world breaks everyone, and afterward, some are strong at the broken places.", topic: "strength", author: "Ernest Hemingway" },
  { text: "Courage isn't having the strength to go on—it is going on when you don't have strength.", topic: "strength", author: "Napoleon Bonaparte" },
  { text: "Strength and growth come only through continuous effort and struggle.", topic: "strength", author: "Napoleon Hill" },
  { text: "You never know how strong you are until being strong is your only choice.", topic: "strength", author: "Bob Marley" },
  { text: "In the depth of winter, I finally learned that within me there lay an invincible summer.", topic: "strength", author: "Albert Camus" },
  { text: "Strength is a matter of a made-up mind.", topic: "strength", author: "John Beecher" },
  { text: "We are only as strong as we are united, as weak as we are divided.", topic: "strength", author: "J.K. Rowling" },


  
  // --- Dreams ---
  { text: "All our dreams can come true, if we have the courage to pursue them.", topic: "dreams", author: "Walt Disney" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", topic: "dreams", author: "Eleanor Roosevelt" },
  { text: "You are never too old to set another goal or to dream a new dream.", topic: "dreams", author: "C.S. Lewis" },
  { text: "A dream you dream alone is only a dream. A dream you dream together is reality.", topic: "dreams", author: "John Lennon" },
  { text: "Dream as if you'll live forever. Live as if you'll die today.", topic: "dreams", author: "James Dean" },
  { text: "Hold fast to dreams, for if dreams die, life is a broken-winged bird that cannot fly.", topic: "dreams", author: "Langston Hughes" },
  { text: "The only thing that will stop you from fulfilling your dreams is you.", topic: "dreams", author: "Tom Bradley" },
  { text: "Dreams are the touchstones of our character.", topic: "dreams", author: "Henry David Thoreau" },
  { text: "Every great dream begins with a dreamer.", topic: "dreams", author: "Harriet Tubman" },
  { text: "Don't let your dreams be dreams.", topic: "dreams", author: "Jack Johnson" },
  { text: "Dreams are illustrations from the book your soul is writing about you.", topic: "dreams", author: "Marsha Norman" },
  { text: "The biggest adventure you can take is to live the life of your dreams.", topic: "dreams", author: "Oprah Winfrey" },

  // --- Belief ---
  { text: "Believe you can and you're halfway there.", topic: "belief", author: "Theodore Roosevelt" },
  { text: "Faith is to believe what you do not see; the reward of this faith is to see what you believe.", topic: "belief", author: "Saint Augustine" },
  { text: "We are twice armed if we fight with faith.", topic: "belief", author: "Plato" },
  { text: "To accomplish great things, we must not only act, but also dream; not only plan, but also believe.", topic: "belief", author: "Anatole France" },
  { text: "Belief creates the actual fact.", topic: "belief", author: "William James" },
  { text: "If you don't stand for something, you will fall for anything.", topic: "belief", author: "Malcolm X" },
  { text: "What you believe, you can achieve.", topic: "belief", author: "Mary Kay Ash" },
  { text: "The moment you doubt whether you can fly, you cease forever to be able to do it.", topic: "belief", author: "J.M. Barrie" },
  { text: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", topic: "belief", author: "Christian D. Larson" },
  { text: "Your beliefs become your thoughts, your thoughts become your words, your words become your actions.", topic: "belief", author: "Mahatma Gandhi" },
  { text: "A man is but the product of his thoughts. What he thinks, he becomes.", topic: "belief", author: "Mahatma Gandhi" },
  { text: "Believe in possibilities, and you'll create opportunities.", topic: "belief", author: "Anonymous" },

  // --- Self-Love ---
  { text: "You yourself, as much as anybody in the entire universe, deserve your love and affection.", topic: "self-love", author: "Buddha" },
  { text: "To love oneself is the beginning of a lifelong romance.", topic: "self-love", author: "Oscar Wilde" },
  { text: "You are enough just as you are.", topic: "self-love", author: "Meghan Markle" },
  { text: "Love yourself first and everything else falls into line.", topic: "self-love", author: "Lucille Ball" },
  { text: "The most powerful relationship you will ever have is the relationship with yourself.", topic: "self-love", author: "Steve Maraboli" },
  { text: "Owning our story and loving ourselves through that process is the bravest thing that we'll ever do.", topic: "self-love", author: "Brené Brown" },
  { text: "You were born to be real, not to be perfect.", topic: "self-love", author: "Anonymous" },
  { text: "Self-love is not selfish; you cannot truly love another until you know how to love yourself.", topic: "self-love", author: "Anonymous" },
  { text: "Be yourself; everyone else is already taken.", topic: "self-love", author: "Oscar Wilde" },
  { text: "To fall in love with yourself is the first secret to happiness.", topic: "self-love", author: "Robert Morley" },
  { text: "You are not a drop in the ocean. You are the entire ocean in a drop.", topic: "self-love", author: "Rumi" },
  { text: "Loving yourself isn't vanity; it's sanity.", topic: "self-love", author: "Katrina Mayer" },

  // --- Authenticity ---
  { text: "Be yourself; everyone else is already taken.", topic: "authenticity", author: "Oscar Wilde" },
  { text: "The privilege of a lifetime is to become who you truly are.", topic: "authenticity", author: "Carl Gustav Jung" },
  { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", topic: "authenticity", author: "Ralph Waldo Emerson" },
  { text: "Authenticity is the daily practice of letting go of who we think we're supposed to be and embracing who we are.", topic: "authenticity", author: "Brené Brown" },
  { text: "Don't trade your authenticity for approval.", topic: "authenticity", author: "Anonymous" },
  { text: "We have to dare to be ourselves, however frightening or strange that self may prove to be.", topic: "authenticity", author: "May Sarton" },
  { text: "The strongest force in the universe is a human being living consistently with his identity.", topic: "authenticity", author: "Tony Robbins" },
  { text: "Authenticity is a collection of choices that we have to make every day.", topic: "authenticity", author: "Brené Brown" },
  { text: "Always be a first-rate version of yourself, instead of a second-rate version of somebody else.", topic: "authenticity", author: "Judy Garland" },
  { text: "Our true identity is to love without fear and insecurity. Our higher potential finds us when we set our course in that direction.", topic: "authenticity", author: "Marianne Williamson" },
  { text: "Authenticity is the alignment of head, mouth, heart, and feet—thinking, saying, feeling, and doing the same thing.", topic: "authenticity", author: "Lance Secretan" },
  { text: "No one man can, for any considerable time, wear one face to himself, and another to the multitude, without finally getting bewildered as to which is the true one.", topic: "authenticity", author: "Nathaniel Hawthorne" },

  // --- Simplicity ---
  { text: "Simplicity is the ultimate sophistication.", topic: "simplicity", author: "Leonardo da Vinci" },
  { text: "The art of simplicity is a puzzle of complexity.", topic: "simplicity", author: "Douglas Horton" },
  { text: "Life is really simple, but we insist on making it complicated.", topic: "simplicity", author: "Confucius" },
  { text: "Simplicity is the keynote of all true elegance.", topic: "simplicity", author: "Coco Chanel" },
  { text: "The greatest wealth is to live content with little.", topic: "simplicity", author: "Plato" },
  { text: "Simplicity is the glory of expression.", topic: "simplicity", author: "Walt Whitman" },
  { text: "In character, in manner, in style, in all things, the supreme excellence is simplicity.", topic: "simplicity", author: "Henry Wadsworth Longfellow" },
  { text: "Simplicity is the essence of happiness.", topic: "simplicity", author: "Cedric Bledsoe" },
  { text: "The ability to simplify means to eliminate the unnecessary so that the necessary may speak.", topic: "simplicity", author: "Hans Hofmann" },
  { text: "There is no greatness where there is not simplicity, goodness, and truth.", topic: "simplicity", author: "Leo Tolstoy" },
  { text: "Simplicity is an acquired taste. Mankind, left free, instinctively complicates life.", topic: "simplicity", author: "Katharine Fullerton Gerould" },
  { text: "Simplicity is the final achievement. After one has played a vast quantity of notes and more notes, it is simplicity that emerges as the crowning reward of art.", topic: "simplicity", author: "Frédéric Chopin" },

  // --- Unity ---
  { text: "We are only as strong as we are united, as weak as we are divided.", topic: "unity", author: "J.K. Rowling" },
  { text: "Coming together is a beginning; keeping together is progress; working together is success.", topic: "unity", author: "Henry Ford" },
  { text: "Unity is strength… when there is teamwork and collaboration, wonderful things can be achieved.", topic: "unity", author: "Mattie Stepanek" },
  { text: "We must learn to live together as brothers or perish together as fools.", topic: "unity", author: "Martin Luther King Jr." },
  { text: "The beauty of the world lies in the diversity of its people, united in purpose.", topic: "unity", author: "Anonymous" },
  { text: "Unity does not mean sameness. It means oneness of purpose.", topic: "unity", author: "Priscilla Shirer" },
  { text: "In union there is strength.", topic: "unity", author: "Aesop" },
  { text: "We are each other's harvest; we are each other's business; we are each other's magnitude and bond.", topic: "unity", author: "Gwendolyn Brooks" },
  { text: "Society is unity in diversity.", topic: "unity", author: "George Herbert Mead" },
  { text: "When there is no enemy within, the enemies outside cannot hurt you.", topic: "unity", author: "Winston Churchill" },
  { text: "Unity to be real must stand the severest strain without breaking.", topic: "unity", author: "Mahatma Gandhi" },
  { text: "Together we can do so much; alone we can do so little.", topic: "unity", author: "Helen Keller" },

  // --- Vision ---
  { text: "The only thing worse than being blind is having sight but no vision.", topic: "vision", author: "Helen Keller" },
  { text: "Vision is the art of seeing what is invisible to others.", topic: "vision", author: "Jonathan Swift" },
  { text: "Where there is no vision, there is no hope.", topic: "vision", author: "George Washington Carver" },
  { text: "The greatest leaders are those most able to translate vision into reality.", topic: "vision", author: "Warren Bennis" },
  { text: "A vision is not just a picture of what could be; it is an appeal to our better selves.", topic: "vision", author: "Rosabeth Moss Kanter" },
  { text: "Your vision will become clear only when you look into your heart.", topic: "vision", author: "Carl Gustav Jung" },
  { text: "The very essence of leadership is that you have to have vision. You can't blow an uncertain trumpet.", topic: "vision", author: "Theodore Hesburgh" },
  { text: "Vision without action is merely a dream. Action without vision just passes the time. Vision with action can change the world.", topic: "vision", author: "Joel A. Barker" },
  { text: "The best way to predict the future is to create it.", topic: "vision", author: "Peter Drucker" },
  { text: "A leader has the vision and conviction that a dream can be achieved.", topic: "vision", author: "Ralph Lauren" },
  { text: "Chase the vision, not the money; the money will end up following you.", topic: "vision", author: "Tony Hsieh" },
  { text: "Create your future from your future, not your past.", topic: "vision", author: "Werner Erhard" },

  // --- Acceptance ---
  { text: "The art of acceptance is the art of making someone who has just done you a small favor wish that he might have done you a greater one.", topic: "acceptance", author: "Martin Luther King Jr." },
  { text: "Acceptance doesn't mean resignation; it means understanding that something is what it is and that there's got to be a way through it.", topic: "acceptance", author: "Michael J. Fox" },
  { text: "The first step toward change is awareness. The second step is acceptance.", topic: "acceptance", author: "Nathaniel Branden" },
  { text: "Acceptance is not love. You love a person because he or she has lovable traits, but you accept everybody just because they're alive and human.", topic: "acceptance", author: "Albert Ellis" },
  { text: "Happiness can exist only in acceptance.", topic: "acceptance", author: "George Orwell" },
  { text: "Acceptance of what has happened is the first step to overcoming the consequences of any misfortune.", topic: "acceptance", author: "William James" },
  { text: "To be fully seen by somebody, then, and be loved anyhow—this is a human offering that can border on miraculous.", topic: "acceptance", author: "Elizabeth Gilbert" },
  { text: "Acceptance is the key to everything.", topic: "acceptance", author: "Michael J. Fox" },
  { text: "Understanding is the first step to acceptance, and only with acceptance can there be recovery.", topic: "acceptance", author: "J.K. Rowling" },
  { text: "The greatest gift that you can give to others is the gift of unconditional love and acceptance.", topic: "acceptance", author: "Brian Tracy" },
  { text: "Acceptance is simply a refusal to be in an adversarial relationship to reality.", topic: "acceptance", author: "Anonymous" },
  { text: "Serenity comes when you trade expectations for acceptance.", topic: "acceptance", author: "Anonymous" },

  // --- Service ---
  { text: "The best way to find yourself is to lose yourself in the service of others.", topic: "service", author: "Mahatma Gandhi" },
  { text: "The life of man is of no greater duration than the breath of his nostrils.", topic: "service", author: "Plato" },
  { text: "Service to others is the rent you pay for your room here on earth.", topic: "service", author: "Muhammad Ali" },
  { text: "The greatest among you will be your servant.", topic: "service", author: "Jesus Christ" },
  { text: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", topic: "service", author: "Ralph Waldo Emerson" },
  { text: "Only a life lived for others is a life worthwhile.", topic: "service", author: "Albert Einstein" },
  { text: "The highest of distinctions is service to others.", topic: "service", author: "King George VI" },
  { text: "We make a living by what we get, but we make a life by what we give.", topic: "service", author: "Winston Churchill" },
  { text: "Service is the very purpose of life. It is the rent we pay for living on this planet.", topic: "service", author: "Marian Wright Edelman" },
  { text: "The true meaning of life is to plant trees, under whose shade you do not expect to sit.", topic: "service", author: "Nelson Henderson" },
  { text: "No one has ever become poor by giving.", topic: "service", author: "Anne Frank" },
  { text: "The best way to not feel hopeless is to get up and do something.", topic: "service", author: "Barack Obama" },

  // --- Humor ---
  { text: "A day without laughter is a day wasted.", topic: "humor", author: "Charlie Chaplin" },
  { text: "Life is too important to be taken seriously.", topic: "humor", author: "Oscar Wilde" },
  { text: "I love people who make me laugh. I honestly think it's the thing I like most, to laugh.", topic: "humor", author: "Audrey Hepburn" },
  { text: "Humor is mankind's greatest blessing.", topic: "humor", author: "Mark Twain" },
  { text: "If you aren't impressed with the picture of the Sistine Chapel you have not seen it; if you are, you haven't understood it.", topic: "humor", author: "G.K. Chesterton" },
  { text: "The most wasted of all days is one without laughter.", topic: "humor", author: "E.E. Cummings" },
  { text: "Laughter is an instant vacation.", topic: "humor", author: "Milton Berle" },
  { text: "Humor is just another defense against the universe.", topic: "humor", author: "Mel Brooks" },
  { text: "A sense of humor is just common sense, dancing.", topic: "humor", author: "William James" },
  { text: "Laughter is the shortest distance between two people.", topic: "humor", author: "Victor Borge" },
  { text: "Humor is the great thing, the saving thing after all.", topic: "humor", author: "Mark Twain" },
  { text: "You can't stay mad at somebody who makes you laugh.", topic: "humor", author: "Jay Leno" }

];